# Generated by Django 3.1.1 on 2020-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Punishment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mc_username", models.CharField(max_length=16)),
                ("mc_uuid", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=255)),
                (
                    "proof",
                    models.CharField(default="Awaiting Proof Upload", max_length=255),
                ),
                ("punished_by", models.CharField(max_length=16)),
                ("punished_by_uuid", models.CharField(max_length=255)),
                (
                    "removed_by",
                    models.CharField(blank=True, default=None, max_length=16),
                ),
                (
                    "removed_by_uuid",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires", models.DateTimeField()),
                ("date_punished", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
