# Generated by Django 3.1.1 on 2020-09-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_punishment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punishment",
            name="proof",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="punishment",
            name="removed_by",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="punishment",
            name="removed_by_uuid",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
